# Generated by Django 3.0.3 on 2020-02-23 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('email', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='', max_length=100)),
                ('lastName', models.CharField(default='', max_length=100)),
                ('major', models.CharField(default='', max_length=100)),
                ('year', models.CharField(default='', max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('disabled', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=100)),
                ('confusionMeter', models.IntegerField(default=0)),
                ('studentEmail', models.CharField(default='', max_length=100)),
                ('tutorEmail', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('email', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='', max_length=100)),
                ('lastName', models.CharField(default='', max_length=100)),
                ('major', models.CharField(default='', max_length=100)),
                ('year', models.CharField(default='', max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('disabled', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TutorCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(default='', max_length=100)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to='QuickTutor.Tutor')),
            ],
        ),
        migrations.CreateModel(
            name='RequestCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(default='', max_length=100)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='QuickTutor.StudentRequest')),
            ],
        ),
    ]
