# Generated by Django 3.0.3 on 2020-02-17 20:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='', max_length=100)),
                ('lastName', models.CharField(default='', max_length=100)),
                ('major', models.CharField(default='', max_length=100)),
                ('year', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('disabled', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='studentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=100)),
                ('confusionMeter', models.IntegerField(default=0)),
                ('studentID', models.UUIDField(default=uuid.uuid4)),
                ('tutorID', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='', max_length=100)),
                ('lastName', models.CharField(default='', max_length=100)),
                ('major', models.CharField(default='', max_length=100)),
                ('year', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('disabled', models.IntegerField(default=0)),
            ],
        ),
    ]
