# Generated by Django 3.0.3 on 2020-02-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='ID',
        ),
        migrations.AddField(
            model_name='tutor',
            name='USER_ID',
            field=models.IntegerField(default=8223464, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='USER_ID',
            field=models.IntegerField(default=6577151, primary_key=True, serialize=False),
        ),
    ]
