# Generated by Django 3.0.4 on 2020-03-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
