# Generated by Django 3.0.3 on 2020-02-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentrequest',
            old_name='subject',
            new_name='courseName',
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='header',
            field=models.CharField(default='', max_length=100),
        ),
    ]
