# Generated by Django 3.0.2 on 2020-02-03 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0002_suggestion_suggestionset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='suggestion_set',
        ),
        migrations.DeleteModel(
            name='SuggestionSet',
        ),
    ]
