# Generated by Django 3.0.2 on 2020-03-29 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0002_auto_20200329_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='request',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='QuickTutor.StudentRequest'),
        ),
    ]
