# Generated by Django 3.0.3 on 2020-04-03 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0002_auto_20200403_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='request',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuickTutor.StudentRequest'),
        ),
    ]
