# Generated by Django 3.0.2 on 2020-03-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0003_auto_20200229_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='studentUsername',
            field=models.CharField(default='', max_length=10),
        ),
    ]
