# Generated by Django 3.0.4 on 2020-03-30 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0003_auto_20200329_1951'),
        ('QuickTutor', '0002_studentrequest_status'),
    ]

    operations = [
    ]
