# Generated by Django 3.0.3 on 2020-03-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0003_auto_20200303_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='meetingDetails',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
