# Generated by Django 3.0.3 on 2020-02-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0003_auto_20200217_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ID',
            field=models.IntegerField(default=2090998, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='ID',
            field=models.IntegerField(default=5957852, primary_key=True, serialize=False),
        ),
    ]
