# Generated by Django 3.0.2 on 2020-03-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0004_studentrequest_studentusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='tutorUsername',
            field=models.CharField(default='', max_length=10),
        ),
    ]
