# Generated by Django 3.0.2 on 2020-03-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0004_merge_20200330_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='tutorEmail',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='tutorUsername',
            field=models.CharField(default='', max_length=10),
        ),
    ]
