# Generated by Django 3.0.3 on 2020-02-11 05:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0005_auto_20200210_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='UUID',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='UUID',
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
