# Generated by Django 3.0.3 on 2020-04-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0005_auto_20200403_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='UUID',
            field=models.CharField(default='', max_length=100),
        ),
    ]
