# Generated by Django 3.0.2 on 2020-03-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0005_studentrequest_tutorusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='accepted',
            field=models.IntegerField(default=0),
        ),
    ]
