# Generated by Django 3.0.3 on 2020-02-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0005_auto_20200217_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ID',
            field=models.IntegerField(default=1485287, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='ID',
            field=models.IntegerField(default=9467629, primary_key=True, serialize=False),
        ),
    ]
