# Generated by Django 3.0.2 on 2020-02-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0006_auto_20200222_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='USER_ID',
            field=models.IntegerField(default=9918249, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='USER_ID',
            field=models.IntegerField(default=7172099, primary_key=True, serialize=False),
        ),
    ]
