# Generated by Django 3.0.3 on 2020-02-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0006_auto_20200211_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='disabled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='matchedID',
            field=models.UUIDField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutor',
            name='disabled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutor',
            name='matchedID',
            field=models.UUIDField(default=0),
        ),
        migrations.AddField(
            model_name='tutor',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
