# Generated by Django 3.0.3 on 2020-02-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0006_auto_20200217_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ID',
            field=models.IntegerField(default=9117034, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='ID',
            field=models.IntegerField(default=6725941, primary_key=True, serialize=False),
        ),
    ]
