# Generated by Django 3.0.3 on 2020-02-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0007_auto_20200211_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tutor',
            name='major',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tutor',
            name='year',
            field=models.CharField(default='', max_length=100),
        ),
    ]
