# Generated by Django 3.0.3 on 2020-02-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0008_auto_20200211_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=100)),
                ('confusionMeter', models.IntegerField(default=0)),
            ],
        ),
    ]
