# Generated by Django 3.0.3 on 2020-02-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0009_studentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='studentID',
            field=models.UUIDField(default=0),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='tutorID',
            field=models.UUIDField(default=0),
        ),
    ]
