# Generated by Django 3.0.4 on 2020-04-14 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0009_auto_20200414_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='sessionElapsedTime',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='sessionEndTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 14, 12, 56, 37, 929582)),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='sessionStartTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 14, 12, 56, 37, 929582)),
        ),
    ]
