# Generated by Django 3.0.3 on 2020-02-17 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0011_auto_20200217_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='id',
            new_name='USER_ID',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='id',
            new_name='USER_ID',
        ),
    ]
