# Generated by Django 3.0.2 on 2020-02-23 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0011_auto_20200222_1646'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='TutorCourse',
        ),
        migrations.RemoveField(
            model_name='studentrequest',
            name='courseName',
        ),
        migrations.AlterField(
            model_name='student',
            name='USER_ID',
            field=models.IntegerField(default=3651243, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='USER_ID',
            field=models.IntegerField(default=7052496, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='RequestCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(default='', max_length=100)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='QuickTutor.StudentRequest')),
            ],
        ),
    ]
