# Generated by Django 3.0.3 on 2020-02-17 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0012_auto_20200217_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='USER_ID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='USER_ID',
            new_name='ID',
        ),
    ]
