# Generated by Django 3.0.4 on 2020-04-14 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0013_auto_20200414_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='sessionEnded',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='sessionEndTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 14, 13, 11, 40, 470997)),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='sessionStartTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 14, 13, 11, 40, 470997)),
        ),
    ]
