# Generated by Django 3.0.3 on 2020-02-17 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0013_auto_20200217_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='matchedID',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='matchedID',
        ),
    ]
