# Generated by Django 3.0.4 on 2020-04-14 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0015_auto_20200414_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='sessionEndTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 14, 13, 26, 11, 477121)),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='sessionStartTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 14, 13, 26, 11, 477121)),
        ),
    ]
