# Generated by Django 3.0.3 on 2020-04-14 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0017_auto_20200414_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='deleteStatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='sessionEndTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 14, 15, 46, 47, 695847)),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='sessionStartTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 14, 15, 46, 47, 695847)),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
