# Generated by Django 3.0.2 on 2020-04-17 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0019_auto_20200417_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='requestTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 17, 17, 0, 42, 789283)),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='sessionEndTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 17, 17, 0, 42, 789479)),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='sessionStartTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 17, 17, 0, 42, 789449)),
        ),
    ]
