# Generated by Django 3.0.2 on 2020-04-20 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0020_auto_20200417_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='requestTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 19, 20, 36, 3, 45957)),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='sessionEndTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 19, 20, 36, 3, 46175)),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='sessionStartTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 19, 20, 36, 3, 46143)),
        ),
    ]
