# Generated by Django 3.0.3 on 2020-04-22 17:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0021_auto_20200419_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderEmail', models.CharField(default='', max_length=100)),
                ('recieverEmail', models.CharField(default='', max_length=100)),
                ('msg_content', models.CharField(default='', max_length=1000)),
                ('created_at', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='requestTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 22, 13, 32, 33, 374790)),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='sessionEndTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 22, 13, 32, 33, 375789)),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='sessionStartTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 22, 13, 32, 33, 375789)),
        ),
        migrations.AlterField(
            model_name='tutorcourse',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuickTutor.Tutor'),
        ),
    ]
