# Generated by Django 3.0.2 on 2020-04-26 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0024_auto_20200426_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='requestTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 14, 30, 45, 14202)),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='sessionEndTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 26, 14, 30, 45, 14364)),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='sessionStartTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 26, 14, 30, 45, 14328)),
        ),
    ]
