# Generated by Django 3.0.3 on 2020-04-26 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0024_auto_20200426_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='requestTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 26, 17, 56, 46, 230859)),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='sessionEndTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 26, 17, 56, 46, 230859)),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='sessionStartTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 26, 17, 56, 46, 230859)),
        ),
    ]
