# Generated by Django 3.0.3 on 2020-04-26 21:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0024_auto_20200426_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='requestTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 21, 42, 19, 322820, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='sessionEndTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 26, 17, 42, 19, 322820)),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='sessionStartTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 26, 17, 42, 19, 322820)),
        ),
    ]
