# Generated by Django 3.0.2 on 2020-04-26 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0025_auto_20200426_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='requestTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 26, 17, 45, 36, 408037)),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='sessionEndTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 26, 17, 45, 36, 408177)),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='sessionStartTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 26, 17, 45, 36, 408145)),
        ),
    ]
